services:
  postgres:
    image: postgres:18
    container_name: game_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gamedb
    ports:
      - "5433:5432"
    volumes:
      - gamedb_postgres_data:/var/lib/postgresql
    restart: unless-stopped

volumes:
  gamedb_postgres_data:
